### ISSUE TITLE
Can not connect preview application

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iotc-explorer#22]
When connect to (pnp) preview application, I got error.

```
C:\>iotc-explorer login "SharedAccessSignature sr=xxxxxxxx-933c-420d-9ba6-7191c2c306b6&sig=HsQBv5EsQiiAUNW9Yiea%2B1MrWma8%2BVG8DLm%2BwhlJbWM%3D&skn=test&se=1607599693562"
Error: IoT Central API call failed with message Authorization token does not have access to path. [IOTC_API_ERROR]

C:\>
```

**Comment by princjef** [comment]
@matsujirushi this tool is only compatible with non-preview IoT Central applications. You can access the same functionality for both preview and non-preview applications through the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) with the following commands:

- [`az iot central app monitor-events`](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/central/app?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-central-app-monitor-events)
- [`az iot central device-twin show`](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/central/device-twin?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-central-device-twin-show)

**Comment by Jackbk** [comment]
Hi @matsujirushi , to add on to what @princjef said this functionality is supported through the [Azure IoT CLI Extension](https://github.com/Azure/azure-iot-cli-extension) which needs to be installed on top of the Azure CLI.  You can find installation instructions for it [here](https://github.com/Azure/azure-iot-cli-extension).

**Comment by matsujirushi** [comment]
I see.
Thanks for your help.
